using Content.Client.UserInterface.Controls;
using Content.Shared.UndecidedLoadout;
using Content.Client.UndecidedLoadout;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UndecidedLoadout;

[GenerateTypedNameReferences]
public sealed partial class UndecidedLoadoutBackpackMenu : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    private readonly SpriteSystem _spriteSystem;

    private readonly UndecidedLoadoutBackpackBoundUserInterface _owner;

    public UndecidedLoadoutBackpackMenu(UndecidedLoadoutBackpackBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();

        _owner = owner;

        ApproveButton.OnButtonDown += (args) =>
        {
            _owner.SendApprove();
        };
    }

    public void UpdateState(UndecidedLoadoutBackpackBoundUserInterfaceState state)
    {
        SetsGrid.RemoveAllChildren();
        int count = 0;
        int selectedNumber = 0;
        foreach (var set in state.Sets)
        {
            var child = new UndecidedLoadoutBackpackSet(set.Value, _spriteSystem);

            child.SetButton.OnButtonDown += (args) =>
            {
                _owner.SendChangeSelected(set.Key);
            };

            SetsGrid.AddChild(child);

            count++;

            if (set.Value.Selected)
                selectedNumber++;
        }

        SelectedSets.Text = Loc.GetString("undecided-loadout-window-selected", ("selectedCount", selectedNumber), ("maxCount", state.MaxSelectedSets));
        ApproveButton.Disabled = selectedNumber == state.MaxSelectedSets ? false : true;
    }
}
